services:
  - type: web
    name: naruto-rpg-service
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: MONGO_URI
        value: mongodb+srv://narutoadmin:NarutoRPG2026Konoha@cluster0.u9ymx75.mongodb.net/narutoGame?retryWrites=true&w=majority&appName=Cluster0
      - key: SELF_URL
        value: https://your-naruto-rpg-app.onrender.com
        
